RAM

\ bag to draw random room ids from
32 bag: room-bag
: fill-room-bag 32 room-bag fill-bag ;

ROM

start-strings
  -" Cellar"
  -" Infirmary"
  -" Library"
  -" Observatory"
  -" Treasury"
  -" Dimly Lit Room"
  -" Tower"
  -" Boiler Room"
  -" Art Gallery"
  -" Catacombs"
  -" Attic"
  -" Corridor"
  -" Tunnel"
  -" Hall"
  -" Ballroom"
  -" Dining Room"
  -" Dressing Room"
  -" Chapel"
  -" Pantry"
  -" Lavatory"
  -" Bed Chambers"
  -" Dungeon"
  -" Courtyard"
  -" Nursery"
  -" Owlery"
  -" Watchtower"
  -" Stables"
  -" Solar"
  -" Kitchens"
  -" Cabinets"
  -" Buttery"
  -" Oratory"
end-strings: roomid>name

start-strings
  -" The sound of bubbling reaches your ears. You see a cauldron in the middle of the room, surrounded by herbs and bones of creatures you've never seen before."
  -" Empty beds line the walls, their sheets ruffled and stained. Near the entrance, rusted instruments lay scattered on a forgotten operating table... Are those blood stains?"
  -" Piles and piles of books cover every last corner of the library. If only you had time to sit in the armchair and dive into the adventures hidden in the dusty pages..."
  -" The sun, the moon, and every last planet of our solar system greet you as the observatory opens before your eyes. Even the ceiling sparkles with a thousand stars."
  -" You squint your eyes as you get blinded by the sudden brightness of the golden walls around you, adorned by thousands of gemstones."
  -" The room before you is dark as the night, the only light source in it a chandelier in which a single candle flickers faintly. Something about this feels sinister."
  -" Soft rustling of something leathery reaches your ears, and you notice a hundred bats hanging right above your head. Please be fruit bats, please be fruit bats..."
  -" A loud roar and a puff stop you in your tracks. Is it a ghoul? Is it a demon? No, just the boiler room of the castle. Phew."
  -" A room full of life-sized portraits piques your curiosity, each painting incredible in its detail. Wait... Did those eyes just move?"
  -" You stagger as something crunches beneath your feet. The floor is uneven: piles of bones cover every inch, not offering a stable ground to walk on."
  -" A small climb later, you find yourself in a dusty attic: the home of badly taxidermied animals with their bead eyes and matted fur."
  -" A long corridor stretches before your eyes, its narrow hallway dark and gloomy. The torches on each side of it offer little light."
  -" The tunnel's ceiling is low, and you can barely stand up straight. Please stay in your webs, spiders! I'm not a fly."
  -" There is not much to see in this small hall: only dried flower arrangements placed on small tables."
  -" This magnificent hall was surely once used to host the most extravagant balls, and you can nearly hear the music from the past."
  -" A table set for a hundred guests sits empty in the middle of the room. The food remains untouched, and the smell of rot makes your stomach churn. I'll stick with crackers for now."
  -" Pearl necklaces, golden crowns, and silk dresses lay abandoned around the room, and you wonder who had once lived here."
  -" Rows after rows of wooden benches sit facing the altar, on which softly flickering candles illuminate a wooden cross."
  -" Bags of wheat and barrels of ale cover every last inch of the pantry. You hear something squeak out of sight."
  -" You discover a hole in the wooden floor. Just as you are about to look down to see where it leads, the smell hits you. Blech!"
  -" A king-sized bed stands in the middle of the room, the satin sheets inviting in their soft sheen. If it wasn't for the skeleton resting in their midst, that is."
  -" Clattering chains hang from the ceiling, and the floor beneath feels sticky with something red. People should be more careful when carrying jars of jam."
  -" Deep green vines climb along an alluring sculpture, its surface tainted grey from the years spent outside. All around her, roses of red and pink bloom in their full glory."
  -" Sudden goosebumps run along your skin, and you quickly uncover the cause: the doll in the middle of the room is keeping an eye on each of your steps. No, thank you!"
  -" Soft hooting of owls, grey and brown and white, drown out all other sounds. It is almost comforting up here, and you fight the urge to curl up on the hay for a nap."
  -" From here, you can see to the furthest ends of the realm. You think you hear an eerie howl coming from the tree line, but by the time you look to see it, it's already gone."
  -" Four horses, bigger than any you’ve ever seen, stomp their hooved feet on the muddy ground as you enter the flimsy stables. If only you had some carrots with you..."
  -" You enter a cosy room decorated with beautiful tapestries. You wish you could take a small break here... The fireplace and furs sure look inviting."
  -" You nearly bump into a clutter of pots, pans, and kettles as you enter the room. The smell of venison stew makes your stomach rumble, yet the pots all seem empty."
  -" You enter a tidy room furnished with books and decorative woodwork. On a desk across from you, an old book seems to be flipping pages on its own."
  -" Barrels stacked high against the walls remind you of the dryness of your tongue. Your steps rushed, you uncork a butt of beer and cherish the taste of the golden liquid."
  -" Artwork of deities you are unfamiliar with covers the walls, the sight breathtaking. The altar seems to be calling for you, sending a shiver down your spine."
end-strings: roomid>desc
